name: serverascode
twitter_username: ccollicutt

#Others
markdown: kramdown

# Syntax highlighting
highlighter: rouge
kramdown:
    input: GFM
    syntax_highlighter: rouge
permalink: /:year/:month/:day/:title.html
future: true